# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-06 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180706_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
    ]
