# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_document_imagecloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
